# Generated by Django 4.2.5 on 2023-10-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_features'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='features',
            options={'verbose_name_plural': 'Features'},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
