# Generated by Django 4.2.5 on 2023-10-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_features_options_alter_subscription_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
