# Generated by Django 4.2.5 on 2023-10-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_course_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='featured_image',
            field=models.ImageField(help_text='This is good', null=True, upload_to='media/featured_image'),
        ),
    ]
