# Generated by Django 4.2.5 on 2023-10-21 20:43

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_course_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
