# Generated by Django 4.2.5 on 2023-10-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_video_time_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='featured_as',
            field=models.CharField(choices=[('NORMAL', 'NORMAL'), ('NEW', 'HOT'), ('HOT', 'HOT'), ('BESTSELLER', 'BESTSELLER')], default='NORMAL', max_length=100, null=True),
        ),
    ]
