# Generated by Django 4.2.5 on 2023-10-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_course_featured_as'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='featured_as',
            field=models.CharField(choices=[('NORMAL', 'NORMAL'), ('NEW', 'NEW'), ('HOT', 'HOT'), ('BESTSELLER', '1')], max_length=100, null=True),
        ),
    ]
