# Generated by Django 4.2.5 on 2023-10-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_course_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='has_completed',
            field=models.BooleanField(default=False),
        ),
    ]
