# Generated by Django 4.2.5 on 2023-10-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_usercourse_has_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
