# Generated by Django 4.2.5 on 2023-10-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_usercourse_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discounted_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
