# Generated by Django 4.2.5 on 2023-10-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_course_discounted_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='example: fa-brands fa-angular', max_length=200, null=True),
        ),
    ]
