# Generated by Django 4.2.5 on 2023-10-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='featured_video',
            field=models.CharField(help_text='eg: https://www.youtube.com/watch?v=6stlCkUDG_s&list=PL4Gr5tOAPttLOY9IrWVjJlv4CtkYI5cI_', max_length=300, null=True),
        ),
    ]
