# Generated by Django 4.2.5 on 2023-10-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_course_featured_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='favorite',
        ),
        migrations.AlterField(
            model_name='course',
            name='featured_as',
            field=models.CharField(choices=[('0', 'NORMAL'), ('3', 'NEW'), ('2', 'HOT'), ('1', 'BESTSELLER')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('PUBLISHED', 'NORMAL'), ('DRAFT', 'DRAFT'), ('LATEST', 'lATEST'), ('FEATURED', 'FEATURED'), ('POPULAR', 'POPULAR')], max_length=100, null=True),
        ),
    ]
