# Generated by Django 4.2.5 on 2023-10-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_course_favorite_alter_course_featured_as_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='iframe',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_url',
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_video_id',
            field=models.CharField(blank=True, help_text='Eg: 9iKZ_uojvxw', max_length=100, null=True),
        ),
    ]
