# Generated by Django 4.2.5 on 2023-10-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_wallpaper',
            field=models.ImageField(null=True, upload_to='media/wallpapers/'),
        ),
    ]
