# Generated by Django 4.2.5 on 2023-10-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_user_wallpaper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_wallpaper',
        ),
    ]
