# Generated by Django 4.2.5 on 2023-10-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='facebook',
            field=models.URLField(blank=True, default='https://facebook.com/', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='github',
            field=models.URLField(blank=True, default='https://github.com', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='x',
            field=models.URLField(blank=True, default='https://x.com/', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='youtube',
            field=models.URLField(blank=True, default='https://youtube.com/', max_length=1000, null=True),
        ),
    ]
