# Generated by Django 4.2.5 on 2023-10-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_facebook_alter_user_github_alter_user_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='media/users/user.png', help_text='Dimension: 415 x 555', null=True, upload_to='media/users/'),
        ),
    ]
