# Generated by Django 4.2.5 on 2023-10-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_instructorapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorapplication',
            name='message',
            field=models.TextField(max_length=500),
        ),
    ]
