# Generated by Django 4.2.5 on 2023-10-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_instructorapplication_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorapplication',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
