# Generated by Django 4.2.5 on 2023-10-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('logo', models.ImageField(upload_to='media/site/')),
                ('site_description', models.TextField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('banner_message', models.CharField(max_length=30)),
                ('facebook', models.URLField(max_length=1000)),
                ('x', models.URLField(max_length=1000)),
                ('linkedin', models.URLField(max_length=1000)),
                ('instagram', models.URLField(max_length=1000)),
            ],
        ),
    ]
