# Generated by Django 4.2.5 on 2023-10-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_sitesetting_google_map_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='banner_message',
            field=models.CharField(max_length=100),
        ),
    ]
