# Generated by Django 4.2.5 on 2023-10-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_alter_sitesetting_homepage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='homepage_image',
            field=models.ImageField(default=0, help_text='Dimensions: 1200 x 1400', upload_to='media/homepage/'),
        ),
    ]
