# Generated by Django 4.2.5 on 2023-10-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
