# Generated by Django 4.2.5 on 2023-10-25 16:07

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_testimonial_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('belongs', models.CharField(choices=[('SITE', 'SITE'), ('OTHER', 'OTHER')], max_length=1000)),
                ('description', tinymce.models.HTMLField()),
            ],
        ),
    ]
